version: '2'
services:
    php:
        build: .
        links:
            - mysql
            - memcached
        volumes:
            - "./wp-content:/var/www/html/wp-content:ro"
            - "./wp-config:/var/www/html/wp-config:ro"
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress

    wpcli:
        build: .
        command: /usr/local/bin/install-multisite
        links:
            - mysql
            - memcached
        volumes:
            - "./wp-content:/var/www/html/wp-content"
            - "./wp-config:/var/www/html/wp-config:ro"
            - ".docker/install-multisite:/usr/local/bin/install-multisite:ro"
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WP_DOMAIN: localhost.localdomain:8000
            WP_ADMIN_USER: wordpress
            WP_EMAIL: wordpress@example.com

    nginx:
        image: nginx:mainline
        volumes:
            - "./wp-content:/var/www/html/wp-content:ro"
            - ".docker/nginx.template:/etc/nginx/conf.d/wordpress.template:ro"
        volumes_from:
            - php:ro
        links:
            - php
        ports:
            - "8000:80"
        command: /bin/bash -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        environment:
            NGINX_PORT: 80

    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    memcached:
        image: memcached
